services:
  # Database
  mysql:
    platform: linux/x86_64
    image: mysql:8.0
    volumes:
      - db_data:/var/lib/mysql
    container_name: mysql
    restart: always
    ports:
      - "3308:3306"
    env_file:
      - .env
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    networks:
      - nest-network

  # phpmyadmin
  phpmyadmin:
    depends_on:
      - mysql
      - nest
    image: phpmyadmin
    container_name: phpmyadmin
    restart: always
    ports:
      - "8099:80"
    env_file:
      - .env
    environment:
      PMA_HOST: ${MYSQL_HOST}
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
    networks:
      - nest-network

  #Nest 
  nest:
    container_name: nest
    image: nest
    build:
      dockerfile: Dockerfile.nest
      context: .
    ports:
      - 3001:3000
    networks:
      - nest-network
    depends_on:
      - mysql
    env_file:
      - .env
    restart: unless-stopped

  #Prisma studio
  prisma-studio:
    links:
      - nest
    depends_on:
      - nest
    image: prisma-studio
    container_name: prisma-studio
    ports:
      - '5558:5558'
    build:
      context: .
      dockerfile: Dockerfile.studio
    env_file:
      - .env
    restart: unless-stopped
    networks:
      - nest-network
    volumes:
      - ./prisma:/app/prisma

networks:
  nest-network:
  external: true 


volumes:
  db_data:
