services:
  # Database
  mysql:
    platform: linux/x86_64
    image: mysql:8.0
    volumes:
      - db_data:/var/lib/mysql
    container_name: mysql
    restart: always
    env_file:
      - .env
    environment:
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    networks:
      - nest-network
    command: --default-authentication-plugin=mysql_native_password 
    healthcheck: # Add healthcheck
      test: ["CMD", "mysqladmin", "ping", "-h", "mysql", "-u", "${MYSQL_USER}", "-p", "${MYSQL_PASSWORD}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 20s # Give MySQL ample time to start initially 

  # phpmyadmin
  phpmyadmin:
    depends_on:
      - mysql
    image: phpmyadmin:latest
    container_name: phpmyadmin
    restart: always
    env_file:
      - .env
    environment:
      PMA_HOST: ${MYSQL_HOST}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    networks:
      - nest-network

  #Nest 
  nest:
    container_name: nest
    image: nest
    build:
      dockerfile: Dockerfile.nest
      context: .
    networks:
      - nest-network
    depends_on:
      mysql:
        condition: service_healthy # But now also waits for health
    env_file:
      - .env
    restart: unless-stopped

  #Prisma studio
  prisma-studio:
    links:
      - nest
    depends_on:
      - nest
    image: prisma-studio
    container_name: prisma-studio
    build:
      context: .
      dockerfile: Dockerfile.studio
    env_file:
      - .env
    restart: unless-stopped
    networks:
      - nest-network
    volumes:
      - ./prisma:/app/prisma

networks:
  nest-network:
    external: true 

volumes:
  db_data:
