services:
  # Database
  mysql:
    platform: linux/x86_64
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    ports:
      - "3308:3306"
    env_file:
      - .env
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    networks:
      - nest-network

  # phpmyadmin
  phpmyadmin:
    depends_on:
      - mysql
    image: phpmyadmin
    container_name: phpmyadmin
    restart: always
    ports:
      - "8099:80"
    env_file:
      - .env
    environment:
      PMA_HOST: ${MYSQL_HOST}
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
    networks:
      - nest-network

  #Nest 
  nest:
    container_name: nest
    image: nest
    build:
      dockerfile: Dockerfile.nest
      context: .
    ports:
      - 3001:3000
      - "5557:5557"
    networks:
      - nest-network

    depends_on:
      - mysql
    env_file:
      - .env
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    restart: unless-stopped

  #Prisma studio
  prisma-studio:
    links:
      - nest
    depends_on:
      - nest
    image: prisma-studio
    container_name: prisma-studio
    ports:
      - '5558:5558'
    build:
      context: .
      dockerfile: Dockerfile.studio
    env_file:
      - .env
    restart: unless-stopped

    networks:
      - nest-network
    volumes:
      - ./prisma:/app/prisma

  rainloop:
    image: hardware/rainloop
    ports:
      - "8087:80"
    networks:
      - nest-network  
    volumes:
      - /mnt/docker/rainloop:/rainloop/data

networks:
  nest-network:

volumes:
  db_data:
