services:
  # Database
  mysql:
    platform: linux/x86_64
    image: mysql:8.0
    volumes:
      - db_data:/var/lib/mysql
    container_name: mysql
    restart: always
    env_file:
      - .env
    environment:
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    networks:
      - nest-network
    command: --default-authentication-plugin=mysql_native_password # Important for compatibility  

  grant-permissions:  
    image: mysql:8.0
    depends_on:
      - mysql 
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    command: [
      "bash",
      "-c",
      "mysql -u root -p$MYSQL_ROOT_PASSWORD -h mysql -e 'GRANT CREATE, ALTER, DROP, INDEX ON collectif.* TO \\'collectif_user\\'@\\'%\\'; FLUSH PRIVILEGES;' && mysql -u root -p$MYSQL_ROOT_PASSWORD -h mysql -e 'SELECT 1 FROM collectif._prisma_migrations' 2>/dev/null && mysql -u root -p$MYSQL_ROOT_PASSWORD -h mysql -e 'GRANT SELECT, INSERT, UPDATE, DELETE ON collectif._prisma_migrations TO \\'collectif_user\\'@\\'%\\'; FLUSH PRIVILEGES;' || true"
    ]
    networks:
      - nest-network

  # phpmyadmin
  phpmyadmin:
    depends_on:
      - mysql
      - nest
    image: phpmyadmin:latest
    container_name: phpmyadmin
    restart: always
    env_file:
      - .env
    environment:
      PMA_HOST: ${MYSQL_HOST}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    networks:
      - nest-network

  #Nest 
  nest:
    container_name: nest
    image: nest
    build:
      dockerfile: Dockerfile.nest
      context: .
    networks:
      - nest-network
    depends_on:
      - mysql
      - grant-permissions
    env_file:
      - .env
    restart: unless-stopped

  #Prisma studio
  prisma-studio:
    links:
      - nest
    depends_on:
      - nest
    image: prisma-studio
    container_name: prisma-studio
    build:
      context: .
      dockerfile: Dockerfile.studio
    env_file:
      - .env
    restart: unless-stopped
    networks:
      - nest-network
    volumes:
      - ./prisma:/app/prisma

networks:
  nest-network:
    external: true 


volumes:
  db_data:
